spring:
  data:
    mongodb:
      uri: mongodb+srv://jenish2312:Jenish2312@cluster0.ddxszfd.mongodb.net/journaldb?retryWrites=false&w=majority&appName=Cluster0
      databse: journaldb
      auto-index-creation : true



server:
  port : 8081
  servlet:
    context-path: /journal